vertex.allow.userMove = true
vertex.radius = 25
vertex.label = true

edge.label = true
edge.arrow = true
edge.label.nodes = false

layout.repulsive-force = 100000
layout.attraction-force = 0.05
layout.attraction-scale = 150