services:
  postgres:
    image: postgres:15
    volumes:
      - db_rutas:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rutas_transporte

volumes:
  db_rutas:

# docker compose up -d